packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@expo/vector-icons': true
  '@react-native/community-cli-plugin': true
  '@react-native/virtualized-lists': true
  '@prisma/client': true
  '@prisma/engines': true
  electron: true
  electron-builder: true
  electron-winstaller: true
  esbuild: true
  expo: true
  prisma: true
  react-native: true
  sharp: true
  unrs-resolver: true
