import { z } from "zod";

/**
 * Venta slice DTOs (interface layer, Unidad 4 + F4b-A order inputs).
 *
 * Edge validation only: strict objects (unknown keys → 422), uuid ids,
 * legacy-exact webshop bodies (duplicated from
 * `modules/webshop/schemas.ts` — the interface skin must not import the
 * module layer, see the gate edge scan). Shapes mirror the application
 * handler inputs (`ConfirmSalesBatchInput`, `CreateOrderInput`,
 * `MintCheckoutSessionInput`) so the router only forwards already-valid
 * payloads, plus the edge-owned `orderId` (uuid v4 generated by the router
 * when the client omits it — legacy clients never send one). Value rules
 * stay in the domain; both layers surface failures as 422 through the
 * frozen envelope.
 */

const uuidMessage = "Identificador inválido: debe ser un uuid";

const ventaLineSchema = z.strictObject({
  productId: z.string().uuid(uuidMessage),
  quantity: z.number().int().min(1, "Cantidad debe ser al menos 1").max(1000)
});

const ventaPaymentSchema = z.strictObject({
  method: z.string().trim().min(1, "method requerido").max(120),
  amount: z.number().nonnegative("amount no puede ser negativo"),
  currency: z.enum(["UYU", "USD", "USDT"])
});

/** Counter (`mostrador`) batch sale → `confirmBatch`. Untouched by F4b-A. */
export const salesBatchBodySchema = z.strictObject({
  ventaId: z.string().uuid(uuidMessage),
  lines: z.array(ventaLineSchema).min(1, "La venta debe tener al menos una línea").max(100),
  payments: z.array(ventaPaymentSchema).min(1, "La venta debe tener al menos un pago").max(100)
});

const orderItemSchema = z.strictObject({
  productId: z.string().uuid("Identificador de producto inválido"),
  quantity: z.number().int().min(1, "Cantidad debe ser al menos 1").max(1000)
});

/** Webshop order → `createOrder` (legacy `orderCreateSchema` + edge orderId). */
export const orderCreateBodySchema = z.strictObject({
  orderId: z.string().uuid(uuidMessage).optional(),
  customer: z.string().min(1, "Cliente requerido").max(160),
  email: z.string().email("Email inválido").max(254).nullish(),
  phone: z.string().max(40).nullish(),
  ci: z.string().max(20).nullish(),
  rut: z.string().max(20).nullish(),
  address: z.string().max(200).nullish(),
  shipping: z.string().max(60).nullish(),
  comments: z.string().max(500).nullish(),
  items: z.array(orderItemSchema).min(1, "El pedido debe tener al menos un artículo").max(100)
});

/** Checkout preference mint → `mintCheckoutSession` (legacy exact). */
export const checkoutSessionBodySchema = z.strictObject({
  orderId: z.string().uuid("Identificador de orden inválido"),
  paymentMethodId: z.string().min(1).max(60).nullish()
});

export type SalesBatchBody = z.infer<typeof salesBatchBodySchema>;
export type OrderCreateBody = z.infer<typeof orderCreateBodySchema>;
export type CheckoutSessionBody = z.infer<typeof checkoutSessionBodySchema>;
